name    'cf-jenkins'
version '0.0.2'

depends 'apt'
depends 'aws'
depends 'chef_handler'
depends 'chef_rubies'
depends 'chef_chruby_install'
depends 'jenkins', '1.2.2'
depends 'selfsigned_certificate'
